acme_alert:
    resource: "@AcmeAlertBundle/Resources/config/routing.yml"
    prefix:   /

acme_profile:
    resource: "@AcmeProfileBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
